add Tabs and countButton
PanVladimir1/react-javascript pull request #3
Opened 2024-01-28 17:43 UTC by PanVladimir1

add Tabs and countButton

2024-01-30 10:51 UTC, SArchieEdu requested changes

2024-01-30 10:51 UTC, SArchieEdu commented on reactApp/src/components/buttonCount/components.jsx
> +    const [disabledMax, setDisabledMax] = useState(false);
эти состояния лишние, тк являются производными от count => их можно всегда вычислить и не хранить. Хрнаить лучше только то, что пользователь нам вводит или подобное

2024-01-30 10:51 UTC, SArchieEdu commented on reactApp/src/components/buttonCount/components.jsx
> +export const ButtonCount = () => {
если выносить эту логику в отдельный компонент, то хотелось бы влиять на минимальное и максимальное значение

2024-01-30 10:51 UTC, SArchieEdu commented on reactApp/src/components/restaurants/component.jsx
>  export const Restaurants = ({restaurants}) => {
сейчас в этом компоненте нет смысла, тк он ничего не делает

2024-01-30 10:51 UTC, SArchieEdu commented on reactApp/src/components/tabs/component.jsx
> +            </div>
лучше в отдельный компонент

2024-02-03 17:37 UTC, PanVladimir1 commented on reactApp/src/components/buttonCount/components.jsx
> +    const [disabledMax, setDisabledMax] = useState(false);
убрал эти состояние minCount и maxCount стал получать через props

2024-02-03 17:37 UTC, PanVladimir1 commented on reactApp/src/components/buttonCount/components.jsx
> +export const ButtonCount = () => {
добавил в пропсы minCount и maxCount

2024-02-03 17:37 UTC, PanVladimir1 commented on reactApp/src/components/restaurants/component.jsx
>  export const Restaurants = ({restaurants}) => {
удалил этот компонент

2024-02-03 17:38 UTC, PanVladimir1 commented on reactApp/src/components/tabs/component.jsx
> +            </div>
вынес в отдельный компонент

2024-02-05 15:29 UTC, SArchieEdu approved these changes

2024-02-05 16:55 UTC, merged